[package]
name = "lhash"
version = "0.0.1"
authors = ["Douman <douman@gmx.se>"]
edition = "2018"
repository = "https://github.com/DoumanAsh/lhash"
description = "Minimal hashing library"
keywords = ["crypto", "cryptography"]
categories = ["cryptography", "no-std"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]

[features]
sha1 = []
md5 = []
hmac = []
